(function () {
  'use strict';
  const chapters = [...(window.CPP_FOUNDATION || []), ...(window.CPP_UNIVERSITY || [])].sort((a,b) => a.number-b.number);
  const lessons = chapters.flatMap(c => c.lessons.map(l => ({...l,chapter:c}))).sort((a,b)=>a.id.localeCompare(b.id));
  const byId = Object.fromEntries(lessons.map(l=>[l.id,l]));
  const main = document.getElementById('main');
  const sidebar = document.getElementById('sidebar');
  const dialog = document.getElementById('search-dialog');
  const KEY = 'cpp-study-v1';
  let state;
  try { state = JSON.parse(localStorage.getItem(KEY) || '{}'); } catch { state = {}; }
  if (!state || typeof state !== 'object' || Array.isArray(state)) state = {};
  state.completed = Array.isArray(state.completed) ? state.completed.filter(id=>byId[id]) : [];
  state.answers = state.answers && typeof state.answers === 'object' ? state.answers : {};
  state.drafts = state.drafts && typeof state.drafts === 'object' ? state.drafts : {};
  let group = 'all', practiceChapter = 'all', practiceStatus = 'all', practicePage = 0, expanded = null, toastTimer, currentId;
  const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const inline = s => esc(s).replace(/&lt;(\/)?(code|strong|em)&gt;/g,'<$1$2>').replace(/&amp;(lt|gt|quot|amp);/g,'&$1;');
  const pad = n => String(n).padStart(2,'0');
  const done = id => state.completed.includes(id);
  function save() { try { localStorage.setItem(KEY,JSON.stringify(state)); return true; } catch { return false; } }
  function toast(text) { const el=document.getElementById('toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2400); }
  function highlight(source) {
    const re = /(\/\/[^\n]*|\/\*[\s\S]*?\*\/|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|^\s*#[^\n]*|\b(?:int|double|float|char|bool|void|auto|const|constexpr|return|if|else|for|while|do|break|continue|switch|case|default|class|struct|public|private|protected|virtual|override|template|typename|new|delete|nullptr|true|false|try|catch|throw|static|using|namespace|explicit|noexcept|enum)\b|\b\d+(?:\.\d+)?\b)/gm;
    let out='',position=0;
    for (const m of source.matchAll(re)) {out+=esc(source.slice(position,m.index));const t=m[0];const kind=t.startsWith('//')||t.startsWith('/*')?'comment':/^["']/.test(t)?'string':/^\s*#/.test(t)?'preprocessor':/^\d/.test(t)?'number':'keyword';out+='<span class="syntax-'+kind+'">'+esc(t)+'</span>';position=m.index+t.length;}
    return out+esc(source.slice(position));
  }
  function codeBlock(code,label) { label=label||(/C\+\+20|#include\s*<(?:concepts|span)>/.test(code)?'C++20 · 使用 -std=c++20':'C++17 · 示例代码');return '<div class="code-block"><div class="code-top"><span>'+esc(label)+'</span><button class="copy-code" type="button">复制代码</button></div><pre><code>'+highlight(code)+'</code></pre></div>'; }
  const footer = () => '<footer class="page-footer"><span>C++ 研习室 · 先理解，再动手，最后解释给自己听。</span><span>核心示例使用 C++17 · C++20 内容另行标注 · 可离线阅读</span></footer>';
  const crumb = title => '<div class="breadcrumb"><a href="#/home">⌂</a><span>/</span>'+title+'</div>';
  function nav() {
    document.getElementById('chapter-nav').innerHTML=chapters.map(c=>'<div class="chapter-group '+(expanded===c.id?'current':'')+'"><div class="chapter-head"><span class="number">'+pad(c.number)+'</span><a href="#/chapter/'+c.id+'">'+esc(c.title)+'</a><button data-expand="'+c.id+'" aria-label="'+(expanded===c.id?'收起':'展开')+esc(c.title)+'" aria-expanded="'+(expanded===c.id)+'">'+(expanded===c.id?'−':'›')+'</button></div>'+(expanded===c.id?'<ul class="lesson-nav">'+c.lessons.map(l=>'<li><a href="#/lesson/'+l.id+'" class="'+(l.id===currentId?'active':'')+'" '+(l.id===currentId?'aria-current="page"':'')+'><span class="done-mark">'+(done(l.id)?'✓':'·')+'</span>'+esc(l.title)+'</a></li>').join('')+'</ul>':'')+'</div>').join('');
    document.getElementById('progress-count').textContent=state.completed.length+' / '+lessons.length;
    document.getElementById('progress-fill').style.width=(state.completed.length/Math.max(1,lessons.length)*100)+'%';
    const bar=document.querySelector('.progress-track');bar.setAttribute('aria-valuemax',lessons.length);bar.setAttribute('aria-valuenow',state.completed.length);
  }
  function closeMenu(){sidebar.classList.remove('open');document.getElementById('scrim').hidden=true;document.getElementById('menu-toggle').setAttribute('aria-expanded','false');}
  function diagram(){return `<svg class="compiler-illustration" viewBox="0 0 580 250" role="img" aria-label="源代码经过编译器生成程序，程序运行后在控制台输出 Hello, C++。"><g stroke="#385347" fill="none"><path d="M8 18h167l22 22v151H8z"/><path d="M175 18v23h22"/><path d="M211 111h31m-8-8 8 8-8 8"/><path d="M258 83h87l13 13v77H245V96z"/><path d="M245 96h113"/><rect x="401" y="65" width="170" height="107" rx="3"/><path d="M371 111h22m-8-8 8 8-8 8"/></g><g font-family="Consolas,monospace" font-size="11"><text x="20" y="57" fill="#527965">#include <tspan fill="#ad6447">&lt;iostream&gt;</tspan></text><text x="20" y="85" fill="#655779">int <tspan fill="#34483a">main() {</tspan></text><text x="26" y="108" fill="#34483a">std::cout &lt;&lt;</text><text x="38" y="129" fill="#ad6447">"Hello, C++!";</text><text x="26" y="153" fill="#655779">return <tspan fill="#ad6447">0;</tspan></text><text x="20" y="176" fill="#34483a">}</text></g><g stroke="#45614f" fill="none" stroke-width="1.6"><circle cx="291" cy="130" r="12"/><circle cx="291" cy="130" r="5"/><path d="M291 112v-5m0 41v5m18-23h5m-41 0h-5m10-13-4-4m30 30 4 4m-4-30 4-4m-30 30-4 4"/><circle cx="324" cy="145" r="8"/><circle cx="324" cy="145" r="3"/><path d="M324 132v-4m0 34v-4m13-13h4m-34 0h4"/></g><circle cx="414" cy="79" r="3" fill="#b96947" stroke="none"/><circle cx="425" cy="79" r="3" fill="#a69d6c" stroke="none"/><circle cx="436" cy="79" r="3" fill="#52745b" stroke="none"/><rect x="410" y="91" width="152" height="71" fill="#243d33" stroke="none"/><g fill="#e1e9dc" font-family="Consolas,monospace" font-size="13"><text x="422" y="120">Hello, C++!</text><text x="422" y="145">&gt; _</text></g><g fill="#677362" stroke="none" text-anchor="middle" font-family="Microsoft YaHei,sans-serif" font-size="12"><text x="101" y="220">源代码（.cpp 文件）</text><text x="302" y="203" fill="#365b43">编译器</text><text x="486" y="202">运行结果</text><text x="486" y="221">控制台输出</text></g></svg>`;}
  function home() {
    const next=byId[state.lastLesson] || lessons.find(l=>!done(l.id)) || lessons[0];
    const selected=chapters.filter(c=>group==='all'||group==='basic'&&c.number<=3||group==='core'&&c.number>=4&&c.number<=8||group==='advanced'&&c.number>=9);
    main.innerHTML='<div class="page-inner home-layout">'+crumb('课程地图')+'<section class="hero"><div><h1>从第一行，<br>开始理解 C++。</h1><p>把程序拆开看，把概念动手试。从基础语法到大学课堂里的核心知识，一步一步学扎实。</p><div class="hero-actions"><a class="button" href="#/lesson/'+(next?.id||'l01')+'">'+(state.lastLesson?'继续学习':'开始第一课')+' <span>→</span></a><a class="text-link" href="#course-map" data-scroll-map>看看学习路线</a></div></div>'+diagram()+'</section><div class="course-facts"><div><div class="fact-main"><strong>'+chapters.length+'</strong> 个章节</div><div class="fact-sub">从基础到实践，逐步深入</div></div><div><div class="fact-main"><strong>'+lessons.length+'</strong> 节讲解</div><div class="fact-sub">读懂示例，试着自己写</div></div><div><div class="fact-main">每节都有练习</div><div class="fact-sub">先想一想，再对照解析</div></div></div><section class="journey"><h2 class="section-heading">'+(state.lastLesson?'接着上次的思路':'你的第一段旅程')+'</h2><div class="journey-strip"><div class="journey-chapter"><span class="journey-number">'+pad(next?.chapter.number||1)+'</span><h3>'+esc(next?.chapter.title||'程序与工具')+'</h3></div><div class="journey-copy"><h3>'+esc(next?.title||'让计算机说出第一句话')+'</h3><p>先读懂一个完整的小程序，再亲手改动它。</p></div><a class="button secondary" href="#/lesson/'+(next?.id||'l01')+'">进入这一课 <span>→</span></a></div></section><section id="course-map"><h2 class="section-heading">课程，一步一步来</h2><p class="section-intro">先打基础，再理解抽象，最后写出完整程序。</p><div class="course-tabs" role="tablist" aria-label="课程阶段">'+[['all','全部课程'],['basic','基础入门'],['core','核心进阶'],['advanced','大学实践']].map(([value,label])=>'<button class="course-tab '+(group===value?'active':'')+'" role="tab" aria-selected="'+(group===value)+'" data-group="'+value+'">'+label+'</button>').join('')+'</div><div class="chapter-list">'+selected.map(c=>'<a class="chapter-row" href="#/chapter/'+c.id+'"><span class="row-number">'+pad(c.number)+'</span><div><h3>'+esc(c.title)+'</h3><p>'+esc(c.description)+'</p><div class="row-meta">'+c.lessons.length+' 节 · '+c.lessons.filter(l=>done(l.id)).length+' 节已完成</div></div><span class="row-arrow">→</span></a>').join('')+'</div></section><aside class="learning-reminder"><svg viewBox="0 0 24 24"><path d="M12 5C8 2 4 3 2 4v16c4-2 7-1 10 1m0-16c4-3 8-2 10-1v16c-4-2-7-1-10 1V5z"/></svg><strong>学习提醒：</strong><span>不用追求“一次就懂”。遇到不理解的地方，动手试一试，改一改，常常会有新的发现。</span></aside>'+footer()+'</div>';
  }
  function chapterView(c){main.innerHTML='<div class="page-inner">'+crumb('<a href="#/home">课程地图</a> / '+esc(c.title))+'<header class="chapter-intro"><span class="big-number">'+pad(c.number)+'</span><h1 class="page-title">'+esc(c.title)+'</h1><p class="page-lead">'+esc(c.description)+'</p><span class="section-intro">'+c.lessons.length+' 节 · 建议按顺序读，遇到疑问可以随时回到上一课。</span></header><ol class="chapter-lessons">'+c.lessons.map((l,i)=>'<li><a class="chapter-lesson" href="#/lesson/'+l.id+'"><span class="lesson-count">'+pad(i+1)+'</span><div class="lesson-content"><h2>'+esc(l.title)+'</h2><p>'+esc(l.lead)+'</p><span class="lesson-time">阅读约 '+l.minutes+' 分钟 · 含示例、自测与练习</span></div>'+(done(l.id)?'<span class="complete-chip">✓ 已完成</span>':'')+'<span class="row-arrow">→</span></a></li>').join('')+'</ol>'+footer()+'</div>';}
  function quizMarkup(l,practice=false){const saved=state.answers[l.id];return '<form class="quiz-card" data-quiz="'+l.id+'"><h2>'+(practice?esc(l.title):'先想一想，再选答案')+'</h2><div class="quiz-kicker">'+(practice?'第 '+pad(l.chapter.number)+' 章 · <a href="#/lesson/'+l.id+'">回到讲解 →</a>':'不必着急，看懂理由比选对更重要。')+'</div><div class="quiz-question">'+esc(l.quiz.question)+'</div><div class="quiz-options">'+l.quiz.options.map((o,i)=>'<label class="quiz-option"><input type="radio" name="quiz-'+l.id+'" value="'+i+'" required '+(saved?.answer===i?'checked':'')+'><span class="option-letter">'+String.fromCharCode(65+i)+'</span><span>'+esc(o)+'</span></label>').join('')+'</div><button class="button small" type="submit">检查答案</button><div class="quiz-feedback-container" aria-live="polite">'+(saved?feedback(l,saved.answer):'')+'</div></form>';}
  function feedback(l,answer){const correct=answer===l.quiz.answer;return '<div class="quiz-feedback '+(correct?'':'wrong')+'"><strong>'+(correct?'✓ 这一步想对了':'再想一想 · 正确答案是 '+String.fromCharCode(65+l.quiz.answer))+'</strong>'+esc(l.quiz.explanation)+'</div>';}
  function exerciseMarkup(l){const seed='#include <iostream>\n\nint main() {\n    // 先写下你的思路，再把它变成代码\n    return 0;\n}\n';return '<section class="exercise-section" id="exercise"><h2>动手写：'+esc(l.exercise.title)+'</h2><p class="exercise-prompt">'+inline(l.exercise.prompt)+'</p><label class="exercise-label" for="draft-'+l.id+'"><span>你的草稿 · '+l.id+'.cpp</span><span id="draft-status">'+(state.drafts[l.id]?'已恢复本地草稿':'输入后自动保存在此浏览器')+'</span></label><textarea id="draft-'+l.id+'" class="code-editor" data-draft="'+l.id+'" spellcheck="false" aria-label="编程练习草稿">'+esc(state.drafts[l.id]||seed)+'</textarea><div class="exercise-actions"><button class="button secondary small" data-download-draft="'+l.id+'">下载我的 .cpp</button><button class="button secondary small" data-download-solution="'+l.id+'">下载参考答案</button></div><p class="editor-note">这里是草稿本。想运行自己写的代码，请下载 .cpp 文件，用本地 C++ 编译器编译。网站里的逐步演示用于观察指定示例，不是通用编译器。<a class="text-link" href="#/lesson/l02">查看环境配置</a></p><details class="solution-details"><summary>卡住了？看一点提示</summary><p>'+inline(l.exercise.hint)+'</p></details><details class="solution-details"><summary>展开完整参考解答</summary>'+codeBlock(l.exercise.solution)+'<p>'+inline(l.exercise.explanation)+'</p></details></section>';}
  function lessonView(l){state.lastLesson=l.id;save();const idx=lessons.findIndex(x=>x.id===l.id),prev=lessons[idx-1],next=lessons[idx+1];let parts=l.sections.map((s,i)=>'<section class="prose-section" id="section-'+i+'"><h2><span class="section-number">'+pad(i+1)+'</span>'+esc(s.title)+'</h2><div class="lesson-body">'+s.paragraphs.map(p=>'<p>'+inline(p)+'</p>').join('')+'</div>'+(s.code?codeBlock(s.code):'')+'</section>').join('');
    main.innerHTML='<div class="article-layout"><article class="lesson-article">'+crumb('<a href="#/chapter/'+l.chapter.id+'">'+esc(l.chapter.title)+'</a> / 本课')+'<div class="lesson-meta"><span>第 '+pad(l.chapter.number)+' 章</span><span>·</span><span>阅读约 '+l.minutes+' 分钟</span><span>·</span><span>含课后自测</span></div><h1>'+esc(l.title)+'</h1><p class="lesson-lead">'+inline(l.lead)+'</p><div class="lesson-tools"><span>阅读字号</span>'+[16,18,20].map(n=>'<button data-font="'+n+'" class="'+((state.font||18)===n?'active':'')+'" aria-label="正文 '+n+' 像素">'+(n===16?'小':n===18?'标准':'大')+'</button>').join('')+'<button class="print-button" data-print>打印本课</button></div><div class="objectives"><h2>这一课，你会弄明白</h2><ul>'+l.objectives.map(s=>'<li>'+inline(s)+'</li>').join('')+'</ul></div>'+parts+'<section class="prose-section" id="example"><h2>把一段完整程序读明白</h2>'+codeBlock(l.example.code)+'<p class="output-label">运行结果 / 示例输入对应的输出</p><pre class="program-output">'+esc(l.example.output)+'</pre><ol class="explanation-list">'+l.example.explanation.map(s=>'<li>'+inline(s)+'</li>').join('')+'</ol></section>'+(l.demo?'<section class="prose-section" id="demonstration"><h2>让过程动起来</h2><div id="lab-mount"></div></section>':'')+'<aside class="pitfall"><strong>这一步容易弄混</strong>'+inline(l.pitfall)+'</aside><section id="self-check">'+quizMarkup(l)+'</section>'+exerciseMarkup(l)+'<div class="lesson-finish"><div><p class="finish-title">'+(done(l.id)?'这一课，已经留下脚印。':'读完了，试着用自己的话解释。')+'</p><p>讲得清为什么，再继续下一课。</p></div><button class="button" data-complete="'+l.id+'">'+(done(l.id)?'✓ 已完成 · 取消标记':'标记为已完成 ✓')+'</button></div><div class="lesson-pagination">'+(prev?'<a href="#/lesson/'+prev.id+'">← '+esc(prev.title)+'</a>':'<a href="#/home">← 课程地图</a>')+(next?'<a href="#/lesson/'+next.id+'">'+esc(next.title)+' →</a>':'<a href="#/practice">去练习本 →</a>')+'</div>'+footer()+'</article><aside class="toc" aria-label="本课内容"><div class="toc-title">这一课的思路</div>'+l.sections.map((s,i)=>'<a href="#section-'+i+'" data-anchor="section-'+i+'">'+esc(s.title)+'</a>').join('')+'<a href="#example" data-anchor="example">完整程序</a>'+(l.demo?'<a href="#demonstration" data-anchor="demonstration">动手观察</a>':'')+'<a class="toc-divider" href="#self-check" data-anchor="self-check">检查理解</a><a href="#exercise" data-anchor="exercise">编程练习</a></aside></div>';
    main.style.setProperty('--reading-size',(state.font||18)+'px');
    if(l.demo&&window.CPPLab)window.CPPLab.render(document.getElementById('lab-mount'),l.demo);
  }
  function practice(){let items=lessons.filter(l=>(practiceChapter==='all'||l.chapter.id===practiceChapter)&&(practiceStatus==='all'||practiceStatus==='wrong'&&state.answers[l.id]?.correct===false||practiceStatus==='correct'&&state.answers[l.id]?.correct===true||practiceStatus==='new'&&!state.answers[l.id]));const pageCount=Math.max(1,Math.ceil(items.length/6));practicePage=Math.min(practicePage,pageCount-1);main.innerHTML='<div class="page-inner">'+crumb('练习本')+'<h1 class="page-title">用问题，检查理解。</h1><p class="page-lead">先独立想一遍，再看解析。做错的题会留在“需要再想想”里，回到对应课文读一读，下次会更清楚。</p><div class="practice-toolbar"><label>学习章节<select id="practice-chapter"><option value="all">全部章节</option>'+chapters.map(c=>'<option value="'+c.id+'" '+(practiceChapter===c.id?'selected':'')+'>'+pad(c.number)+' '+esc(c.title)+'</option>').join('')+'</select></label><label>练习状态<select id="practice-status">'+[['all','全部问题'],['new','还没做过'],['wrong','需要再想想'],['correct','已经想明白']].map(([v,t])=>'<option value="'+v+'" '+(practiceStatus===v?'selected':'')+'>'+t+'</option>').join('')+'</select></label><span class="practice-stat">答对 '+lessons.filter(l=>state.answers[l.id]?.correct).length+' / '+lessons.length+' 题 · 当前 '+items.length+' 题</span></div><div class="practice-grid">'+items.slice(practicePage*6,practicePage*6+6).map(l=>quizMarkup(l,true)).join('')+'</div>'+(items.length?'<div class="pager"><button class="button secondary small" data-practice-page="-1" '+(practicePage===0?'disabled':'')+'>← 上一页</button><span>'+(practicePage+1)+' / '+pageCount+'</span><button class="button secondary small" data-practice-page="1" '+(practicePage>=pageCount-1?'disabled':'')+'>下一页 →</button></div>':'<div class="page-empty"><h2>这里暂时没有问题。</h2><p>换一个章节或练习状态看看。</p></div>')+footer()+'</div>';}
  function labPage(mode){main.innerHTML='<div class="lab-page">'+crumb('代码实验室')+'<h1 class="page-title">让看不见的过程，变得清楚。</h1><p class="page-lead">改一改输入，先预测结果，再点击“下一步”。看着变量、数组和调用栈变化，比只盯着最终答案更容易理解代码。</p><div id="lab-mount"></div><div class="lab-links"><span>相关课程：</span><a href="#/lesson/l05">变量与类型</a><a href="#/lesson/l10">循环</a><a href="#/lesson/l15">递归</a><a href="#/lesson/l22">指针与地址</a><a href="#/lesson/l25">类与对象</a></div>'+footer()+'</div>';if(window.CPPLab)window.CPPLab.render(document.getElementById('lab-mount'),mode||'variables');}
  function route(){const old=document.getElementById('lab-mount');if(old&&window.CPPLab)window.CPPLab.destroy(old);const [page,id]=(location.hash.replace(/^#\/?/,'')||'home').split('/');currentId=null;document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===(page==='lab'?'lab':page==='practice'?'practice':'home')));closeMenu();if(page==='lesson'&&byId[id]){currentId=id;expanded=byId[id].chapter.id;lessonView(byId[id]);}else if(page==='chapter'&&chapters.find(c=>c.id===id)){expanded=id;chapterView(chapters.find(c=>c.id===id));}else if(page==='lab')labPage(id);else if(page==='practice')practice();else home();nav();document.title=(currentId?byId[currentId].title+' · ':'')+'C++ 研习室';window.scrollTo(0,0);}
  function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);toast('已下载 '+name);}
  async function copy(text){try{await navigator.clipboard.writeText(text);}catch{const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.left='-9999px';document.body.append(t);t.select();const ok=document.execCommand('copy');t.remove();if(!ok){toast('请选中代码后按 Ctrl+C 复制');return;}}toast('代码已复制');}
  main.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;if(b.hasAttribute('data-scroll-map')){e.preventDefault();document.getElementById('course-map').scrollIntoView();}else if(b.dataset.group){group=b.dataset.group;const y=window.scrollY;home();window.scrollTo(0,y);}else if(b.dataset.anchor){e.preventDefault();document.getElementById(b.dataset.anchor)?.scrollIntoView();}else if(b.classList.contains('copy-code'))copy(b.closest('.code-block').querySelector('pre').textContent);else if(b.dataset.font){state.font=Number(b.dataset.font);save();main.style.setProperty('--reading-size',state.font+'px');main.querySelectorAll('[data-font]').forEach(el=>el.classList.toggle('active',el===b));}else if(b.hasAttribute('data-print'))window.print();else if(b.dataset.complete){const id=b.dataset.complete;state.completed=done(id)?state.completed.filter(x=>x!==id):[...state.completed,id];save();b.textContent=done(id)?'✓ 已完成 · 取消标记':'标记为已完成 ✓';nav();toast(done(id)?'这一课的进度已记录':'已取消完成标记');}else if(b.dataset.downloadDraft){const id=b.dataset.downloadDraft;download(document.querySelector('[data-draft="'+id+'"]').value,id+'-practice.cpp');}else if(b.dataset.downloadSolution){const id=b.dataset.downloadSolution;download(byId[id].exercise.solution,id+'-solution.cpp');}else if(b.dataset.practicePage){practicePage+=Number(b.dataset.practicePage);practice();window.scrollTo(0,0);}});
  main.addEventListener('submit',e=>{const form=e.target.closest('[data-quiz]');if(!form)return;e.preventDefault();const input=form.querySelector('input:checked');if(!input)return;const l=byId[form.dataset.quiz],answer=Number(input.value);state.answers[l.id]={answer,correct:answer===l.quiz.answer};save();form.querySelector('.quiz-feedback-container').innerHTML=feedback(l,answer);form.querySelector('button[type=submit]').textContent='再检查一次';const stat=document.querySelector('.practice-stat');if(stat)stat.textContent='答对 '+lessons.filter(x=>state.answers[x.id]?.correct).length+' / '+lessons.length+' 题';});
  main.addEventListener('input',e=>{if(e.target.dataset.draft){state.drafts[e.target.dataset.draft]=e.target.value;document.getElementById('draft-status').textContent=save()?'草稿已保存在此浏览器':'浏览器未允许保存，请下载草稿';}});
  main.addEventListener('change',e=>{if(e.target.id==='practice-chapter'){practiceChapter=e.target.value;practicePage=0;practice();}if(e.target.id==='practice-status'){practiceStatus=e.target.value;practicePage=0;practice();}});
  main.addEventListener('keydown',e=>{if(e.target.dataset.draft&&e.key==='Tab'){e.preventDefault();const t=e.target,p=t.selectionStart;t.setRangeText('    ',p,t.selectionEnd,'end');t.dispatchEvent(new Event('input',{bubbles:true}));}});
  document.getElementById('chapter-nav').addEventListener('click',e=>{const b=e.target.closest('[data-expand]');if(b){expanded=expanded===b.dataset.expand?null:b.dataset.expand;nav();}});
  document.getElementById('menu-toggle').addEventListener('click',()=>{const open=!sidebar.classList.contains('open');sidebar.classList.toggle('open',open);document.getElementById('scrim').hidden=!open;document.getElementById('menu-toggle').setAttribute('aria-expanded',open);});
  document.getElementById('scrim').addEventListener('click',closeMenu);
  function search(){const q=document.getElementById('search-input').value.trim().toLowerCase();const found=lessons.filter(l=>!q||[l.title,l.lead,l.chapter.title,...l.sections.flatMap(s=>[s.title,...s.paragraphs])].join(' ').toLowerCase().includes(q)).slice(0,18);document.getElementById('search-results').innerHTML=found.length?found.map(l=>'<a class="search-result" href="#/lesson/'+l.id+'"><small>'+pad(l.chapter.number)+' / '+esc(l.chapter.title)+'</small><h3>'+esc(l.title)+'</h3><p>'+esc(l.lead)+'</p></a>').join(''):'<div class="search-empty">没有找到这个词。试试“数组”“函数”或“内存”。</div>';}
  function openSearch(){dialog.showModal();search();document.getElementById('search-input').focus();}
  document.getElementById('search-open').addEventListener('click',openSearch);
  document.getElementById('search-input').addEventListener('input',search);
  dialog.querySelector('[data-close-dialog]').addEventListener('click',()=>dialog.close());
  dialog.addEventListener('click',e=>{if(e.target.closest('.search-result')){dialog.close();if(e.target.closest('.search-result').hash===location.hash)route();}if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
  document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(!dialog.open)openSearch();}if(e.key==='Escape')closeMenu();});
  window.addEventListener('hashchange',route);
  route();
})();
